name: Deploy to lambda
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy_zip:
    name: Deploy lambda function from ZIP
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Cargo clean
        run: cargo clean
      # - name: Install musl-tools
      #   run: |
      #     set -ex
      #     sudo apt-get update
      #     sudo apt-get install -y musl-tools
      # - run: >
      #     rustup target add
      #     x86_64-unknown-linux-musl
      #     x86_64-unknown-linux-gnux32
      #     x86_64-linux-android
      #     x86_64-apple-darwin
      #     x86_64-unknown-freebsd
      #     x86_64-unknown-netbsd
      #     x86_64-fuchsia
      #     i686-unknown-linux-gnu
      #     i686-unknown-linux-musl
      #     wasm32-unknown-emscripten
      #     riscv64gc-unknown-linux-gnu
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: 1.64.0
          targets: x86_64-unknown-linux-musl
      - name: Build | Check
        run: cargo check
      - name: Build Binary
        run: cargo build

      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r lambda.zip ./targets/x86_64-unknown-linux-musl/release
      - name: Deploy Zip
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: rust-lambda
          zip_file: lambda.zip
          debug: true